language: python
python:
  - "2.7"
  - "3.6"
env:
  matrix:
    - TF_VERSION="1.5.*"
    - TF_VERSION="1.6.*"
    - TF_VERSION="1.7.*"
matrix:
  exclude:
    - python: "3.6"
      env: TF_VERSION="1.5.*"
    - python: "3.6"
      env: TF_VERSION="1.6.*"
install:
  - pip install -q "tensorflow==$TF_VERSION"
  - pip install -q .[tests]
  # Make sure we have the latest version of numpy - avoid problems we were
  # seeing with Python 3
  - pip install -q -U numpy
script:
  # Check import
  - python -c "import kfac; print(kfac.LayerCollection.__name__)"

  # Run tests
  - pytest

git:
  depth: 3
